"""
contacts_wave2.py -- Wave 2 contacts (MX-filtered)
"""

RECRUITERS = [
    ("Pvcleanmobility", "Sourabh Kane", "sourabh.kane@pvcleanmobility.com"),
    ("Autofitltd", "Pawan Kumar", "pawan.kumar@autofitltd.com"),
    ("Pisquaretech", "Dora Srivalli", "srivallid@pisquaretech.com"),
    ("Anandgroupindia", "Khushboo Sidana", "khushboo.sidana@anandgroupindia.com"),
    ("Makinoindia", "Shweta Bansal", "shweta.bansal@makinoindia.com"),
    ("Bluehyundai", "Prajna Jain", "prajna.jain@bluehyundai.co.in"),
    ("Ultraviolette", "Vishakha Mogral", "vishakha.mogral@ultraviolette.com"),
    ("Continental Engines", "Anubhav Pathak", "anubhav.pathak@continental-engines.com"),
    ("Tccimfg", "Prabhat Sharma", "prabhat.sharma@tccimfg.in"),
    ("Varroc", "Dnyaneshwar Rathod", "dnyaneshwar.rathod@varroc.com"),
    ("Reliableautotech", "Jaywant Solankar", "jaywant.solankar@reliableautotech.com"),
    ("Gns India", "Omkar Lokhande", "omkar.lokhande@gns-india.com"),
    ("Saabengg", "Nithya Reddy", "nithya@saabengg.com"),
    ("Bmw Deutschemotoren", "Sunil Sharma", "sunil.sharma@bmw-deutschemotoren.in"),
    ("In", "Amit Singh", "aksingh@in.nifco.com"),
    ("Pravaig", "JK Sahu", "jk.sahu@pravaig.com"),
    ("Omegaseikimobility", "Happy Bhati", "happy@omegaseikimobility.com"),
    ("Omegaseikimobility", "Kapil Rana", "kapil@omegaseikimobility.com"),
    ("Bestex", "Sanjay Lamba", "sanjaylamba@bestex.co.in"),
    ("Electraev", "Nikhil Kumar", "nikhil.kumar@electraev.com"),
    ("Lismail", "Anand R", "anand.pr@lismail.in"),
    ("Konceptmahindra", "Mamta Singh", "mamta.singh@konceptmahindra.com"),
    ("Mahavirauto", "Feeba", "f@mahavirauto.com"),
    ("Wasantoyotamumbai", "Deepak Kapoor", "deepak@wasantoyotamumbai.com"),
    ("Wiggles", "Ashutosh Sinha", "ashutosh.sinha@wiggles.in"),
    ("Pearlpet", "Pearl", "pearl@pearlpet.net"),
    ("Conversejob", "Sakshi Converse", "sakshi@conversejob.com"),
    ("Wiggles", "Tanusree Chanda", "tanusree.chanda@wiggles.in"),
    ("Thehelloworld", "Jaya Parmar", "jaya@thehelloworld.com"),
    ("Dbsmintek", "Manjusha Manne", "manjusha.manne@dbsmintek.com"),
    ("Winnyimmigration", "Winny Department", "departmentw@winnyimmigration.com"),
    ("Tumbledry", "Divya Singh", "divya.singh@tumbledry.in"),
    ("Supertails", "Sukirti Garg", "sukirtilovespets@supertails.com"),
    ("Stockholdingdms", "Mayuri Kothavle", "mayuri.kothavle@stockholdingdms.com"),
    ("Yadavmeasurements", "Rakesh Salvi", "rakesh.salvi@yadavmeasurements.com"),
    ("Thehelloworld", "Karen Lobo", "karen@thehelloworld.com"),
    ("Coutloot", "Srikala Pillai", "srikala@coutloot.com"),
    ("Wiggles", "Vishant Jadhav", "vishant.jadhav@wiggles.in"),
    ("Wiggles", "Gunjan Singh", "gunjan@wiggles.in"),
    ("Conversejob", "Pallavi Bhatnagar", "pallavi@conversejob.com"),
    ("Laundryheap", "Deepti Verma", "deepti@laundryheap.co.uk"),
    ("Mtpl", "Pratiksha Patole", "ppatole@mtpl.org"),
    ("Startv", "Miloni Patil", "miloni.patil@startv.com"),
    ("Eliteindia", "Bijoy Francis", "bijoy.francis@eliteindia.com"),
    ("Skillslash", "Poojashree R", "poojashree.r@skillslash.com"),
    ("Infonativesolutions", "Rajni Vaid", "r.vaid@infonativesolutions.com"),
    ("Phibonacci", "Ruchika Parikh", "ruchika.parikh@phibonacci.com"),
    ("Dbmi", "Nikhil Sharma", "nikhil.sharma@dbmi.edu.in"),
    ("Eluminaelearning", "Venkatesh", "venkatesh@eluminaelearning.com.au"),
    ("Whizlabs", "Navya Vadada", "navya@whizlabs.com"),
    ("Jigsawacademy", "Melissa Pai", "melissa@jigsawacademy.com"),
    ("Mentoria", "Ishaa Shah", "ishaa.shah@mentoria.com"),
    ("Innovalance", "Arshi Dahma", "arshi@innovalance.com"),
    ("Edfora", "Siddharth Dahma", "siddharth.dahma@edfora.com"),
    ("Classteacher", "Shalini Malhotra", "shalini.m@classteacher.com"),
    ("Squarepanda", "Amitha Rajendran", "amitha@squarepanda.com"),
    ("Paradisosolutions", "Urvashi Jibhkate", "urvashi.j@paradisosolutions.com"),
    ("Suraasa", "Neha Gupta", "neha@suraasa.com"),
    ("Codekaroyaaro", "Naman Joshi", "naman@codekaroyaaro.com"),
    ("Infonative", "Arijit Purkayastha", "ap@infonative.net"),
    ("Mindcypress", "Divya Nain", "divya@mindcypress.org"),
    ("Vaidikedu", "Pooja Gupta", "pooja.gupta@vaidikedu.com"),
    ("Classteacher", "Surender Kumar", "surender@classteacher.com"),
    ("Squarepanda", "Minolette Lemos", "minolette@squarepanda.com"),
    ("Apparelresources", "Shipra Grover", "sgrover@apparelresources.com"),
    ("Beyoung", "Charu Singhvi", "charu.singhvi@beyoung.in"),
    ("Coats", "Chitra Dhar", "chitra.dhar@coats.com"),
    ("Menrocks", "Heena Raina", "heena@menrocks.in"),
    ("Neemans", "Kasturi Choudhury", "kasturi@neemans.com"),
    ("Usplworld", "Hedwig Kerketta", "hedwig@usplworld.com"),
    ("John Jacobs", "Shruti Vig", "shruti.vig@john-jacobs.com"),
    ("Sabsexports", "Rajeev Kumar", "rajeev.kumar@sabsexports.com"),
    ("Mirraw", "Trupti Bansode", "trupti.bansode@mirraw.com"),
    ("Gimatex", "Rajiv Sharma", "hrd@gimatex.co.in"),
    ("Maxwellindustries", "Dhana Sekar", "dhana.sekar@maxwellindustries.com"),
    ("Fablestreet", "Charu Vats", "charu.vats@fablestreet.com"),
    ("Bombayshirts", "Pujan Majumdar", "pujan@bombayshirts.com"),
    ("Myblissclub", "Sneha Singh", "snehasingh@myblissclub.in"),
    ("Teamhgs", "Prajakta Dalvi", "prajakta@teamhgs.com"),
    ("Faballey", "Sana Daniel", "sana.daniel@faballey.com"),
    ("Neemans", "Anjan Ribadiya", "anjan@neemans.com"),
    ("Vstar", "Alice George", "alice.george@vstar.in"),
    ("Condorinblu", "Mitul Patel", "mitul@condorinblu.com"),
    ("Beyoung", "Drishti Jain", "drishti@beyoung.in"),
    ("Celebritygroup", "Sankar Shanmugam", "sankar@celebritygroup.com"),
    ("Myblissclub", "Keerthana Aniyan", "keerthana@myblissclub.in"),
    ("Outshiny", "Bharathi R", "bharathi@outshiny.com"),
    ("Aqualiteindia", "Harish Dalal", "harish.dalal@aqualiteindia.com"),
    ("Suta", "Sahithi Vasantharao", "sahithi@suta.in"),
    ("Classicpolos", "Reegan A", "reegan.a@classicpolos.com"),
    ("Geniemode", "Aman Mehta", "aman.mehta@geniemode.com"),
    ("Evelineinternational", "Ajay Bhatia", "ajay@evelineinternational.com"),
    ("Leinershoes", "Kuldeep Yadav", "kuldeep@leinershoes.com"),
    ("Mirraw", "Shivani Maidham", "shivani.maidham@mirraw.com"),
    ("Neemans", "Manjula Soorve", "manjula@neemans.com"),
    ("Ampm", "Ruchi Verma", "ruchi.verma@ampm.in"),
    ("Srinivasafashions", "Jagan Durai", "jagan@srinivasafashions.com"),
    ("Taruntahiliani", "Shivani Saini", "shivani.saini@taruntahiliani.com"),
    ("Neemans", "Ankita Raj", "ankita@neemans.com"),
    ("Lecoanethemant", "Saurav Kumar", "saurav@lecoanethemant.com"),
    ("Magnoliablossom", "Dipak Mehata", "dipak@magnoliablossom.com"),
    ("Ixfi", "Khushboo Shrivastava", "khushboo.s@ixfi.com"),
    ("Basizfa", "Nishith Shetty", "hrmumbai@basizfa.com"),
    ("Aristotleconsultancy", "Pooja Gupta", "pooja.gupta@aristotleconsultancy.com"),
    ("Smcinvestments", "Kanika Sharma", "kanikas@smcinvestments.co.in"),
    ("Numadic", "Siddhi Palekar", "siddhi@numadic.com"),
    ("Definedge", "Rachana Kokate", "rachana.kokate@definedge.com"),
    ("Thegrowtharrow", "Priyanka S", "priyanka@thegrowtharrow.com"),
    ("Pnfp", "Careers Pinnacle", "careers.pinnaclefinancial@pnfp.com"),
    ("Jiraaf", "Sathya Mayalagu", "sathya.m@jiraaf.com"),
    ("Smartowner", "Adnan Khan", "adnan.khan@smartowner.com"),
    ("Fno", "Harshal Shah", "harshal@fno.co"),
    ("Surfboard", "Puja Chakraborty", "puja@surfboard.se"),
    ("Finwaycapital", "Ayushi Soni", "ayushi.soni@finwaycapital.in"),
    ("Moneyhop", "Shradha Lawande", "shradha@moneyhop.co"),
    ("Shriramfinance", "Muthukumar HRD", "hrd@shriramfinance.in"),
    ("Mangalkeshav", "Adhya Shinde", "adhya.shinde@mangalkeshav.com"),
    ("Sunidhi", "Juhi Trivedi", "juhitrivedi@sunidhi.com"),
    ("Technoworld", "Roma Rasal", "rrasal@technoworld.in"),
    ("Bourkegroup", "Nachiket Ingale", "nachiket.ingale@bourkegroup.com.au"),
]
