"""
contacts.py — All recruiter contacts extracted from the document.
Each entry: (company, hr_name_or_none, email)
"""

RECRUITERS = [
    ("Tech Mahindra",               None,       "rajagopalan.ks@techmahindra.com"),
    ("Alliance Global Services",    None,       "pkatkuri@allianceglobalservices.com"),
    ("Cybage",                      None,       "pgarde@cybage.com"),
    ("Calsoft",                     "Ravish Chadha", "Ravish.Chadha@calsoftinc.com"),
    ("Cyient",                      "Aijas Mohammed", "Aijas.Mohammed@cyient.com"),
    ("IBS Software",                "Arun Philip", "arun.philip@ibsplc.com"),
    ("Cruiseline Ship Management",  None,       "hr@cruiselinefoundation.com"),
    ("UXReactor",                   None,       "rmuppala@uxreactor.com"),
    ("Mphasis",                     None,       "Vidyaranya.K@mphasis.com"),
    ("TekSystems",                  None,       "rjena@teksystems.com"),
    ("Inrhythm Solutions",          None,       "umamahesh.tatipati@inrhythm-inc.com"),
    ("MAQ Software",                None,       "aanchalm@maqsoftware.com"),
    ("Genpact",                     None,       "venkat.r@genpact.com"),
    ("ZenQ",                        None,       "azam.ali@zenq.com"),
    ("Mold Tek Technologies",       None,       "rajeev@moldteckindia.com"),
    ("Incessant Technologies",      None,       "sridhars@incessanttechnologies.com"),
    ("NTT Data",                    None,       "prashanth.nidamarthy@nttdata.com"),
    ("Amazon",                      None,       "jainpooj@amazon.com"),
    ("Juspay / GUVI",               None,       "arunpaul@guvi.in"),
    ("Osmosys Software Solutions",  None,       "shujauddin.md@osmosys.asia"),
    ("Epic Research",               None,       "pnaik@epicresearch.co"),
    ("QED Baton",                   "Shreya Adlakha", "shreya.adlakha@qedbaton.com"),
    ("Excers",                      None,       "lohitha.tirunagari@excers.com"),
    ("Globussoft",                  None,       "hr@globussoft.com"),
    ("Uber",                        None,       "bteja@uber.com"),
    ("Aptroid Technologies",        None,       "ryenduri@zetainteractive.com"),
    ("Intone Networks",             None,       "sujith.y@intonenetworks.in"),
    ("Pratian Technologies",        None,       "pattabhi@pratian.com"),
    ("Miracle Software",            None,       "rthamada@miraclesoft.com"),
    ("Zen Technologies",            "Preeti A", "preeti.a@zentechnologies.com"),
    ("Tata Advanced Systems Limited", None,     "kpmohammad@tataadvancedsystems.com"),
    ("Effectronics",                "Samatha J","samatha.j@efftronics.com"),
    ("Broadridge",                  None,       "kumar.nayani@broadridge.com"),
    ("GlobalLogic",                 None,       "gorky.chenna@globallogic.com"),
    ("Sutherland Global",           None,       "Ashwin.Kausic@sutherlandglobal.com"),
    ("HCL Talentcare",              None,       "praveenk.d@hcl.com"),
    ("Intelenet Global",            None,       "seenu.kumar@intelenetglobal.com"),
    ("Energy Infratech",            None,       "satish.kv@energyinfratech.com"),
    ("HCL Tech",                    None,       "mithun.prasad@hcl.com"),
    ("Just Dial",                   None,       "deepika.racherla@justdial.com"),
    ("United Health Group",         None,       "shweta_kochar@uhg.com"),
    ("Sterling & Wilson",           None,       "sharmindamania@sterlingwilson.com"),
    ("CallHealth",                  None,       "saresh.yadagiri@callhealth.co.in"),
    ("Safran (Morpho Group)",       None,       "abhay.singh2@safrangroup.com"),
    ("Rane Group",                  None,       "r.sharmila@ranegroup.com"),
    ("Ramtech",                     None,       "vrkuruhuri@ramtech-corp.com"),
    ("Vem Technologies",            None,       "kvvsatya@vemtechnologies.com"),
    ("Technovert",                  None,       "anoopkesiraju@technovert.com"),
    ("Fujitsu",                     "Akanksha Robert", "Akanksha.Robert@in.fujitsu.com"),
    ("Tata Technologies",           None,       "rohan.gavade@tatatechnologies.com"),
    ("Atos",                        None,       "prakhar.ranjan@atos.net"),
    ("Impelsys",                    None,       "mahesh.nair@impelsys.com"),
    ("Commlab",                     None,       "deepikabaddapuri@commlabindia.com"),
    ("CEI America",                 None,       "jhema@ceiamerica.com"),
    ("Grey Campus",                 None,       "hr@greycampus.com"),
]
