"""
contacts_hr.py -- HR recruiter contacts parsed from contacts/hr_details_contact.csv
"""

RECRUITERS = [
    ("42 Hertz Software India Private Limited", "Mr. Gurunathan", "gurunathan.murugan@aspiringminds.in"),
    ("7Eleven Arthashastra India P Ltd", "Ms. Aishwarya", "placementps@gmail.com"),
    ("Ababil Healthcare Private Limited", None, "hr@ababilhealthcare.com"),
    ("ABS Aircon Engineers P. Ltd.", "Raj Kumar N", "admin.tn@absace.com"),
    ("Aditya Birla Group", "Mr. Karthikeyan", "karthikeyan.g@retail.adityabirla.com"),
    ("Adroitech Engg. Solutions P.Ltd", "Mr. Venkatesa Balakrishnan", "venkatesa.b@adriotecengg.com"),
    ("Airwood", "Abel mathew", "abel@airwood.in"),
    ("Aithent Technologies", "Anusha Nila Mahendran", "manushanila@chn.aithent.com"),
    ("Alcatel (NOKIA) Webcamera Interview", "Kishore Kumar", "kishore.kumar_l.ext@on.nokia.com"),
    ("Alliance Group Companies", "Beni Jebanesan S", "beni@alliancein.com"),
    ("Amara Raja Group", "L Dayakar Reddy", "navaprathibha@amararaja.co.in"),
    ("Amazon", "Arun", "arun@expanion.com"),
    ("Ameex Technologies", "Ms. Uma", "uma.doraiswamy@ameexusa.co"),
    ("American Megatrends India Ltd", "Mr. Ashok Shankar", "ashok.shankar@monsterindia.com"),
    ("Apollo Tyres", "Mr. Prabhakaran", "prabhakaran.dhanushkodi@apollotyres.com"),
    ("Aricent Technologies", "Mr. Megha", "megha.singh@aricent.com"),
    ("ASG Technologies Pvt Ltd.", "Mr. Nagarajan", "nagarajan.jayachandran@formaccorp.com"),
    ("Aspire Systems", "Satish Rajendran |", "satish.rajendran@aspiresys.com"),
    ("Athena Health", "Narayana Jalla", "jnarayana@athenahealth.com"),
    ("Axis Bank", "Nanditha.K", "nandita@tvsts.com"),
    ("Barry Wehmiller", "Jawahar Karthikeyan", "jawahar.karthikeyan@bwir.com"),
    ("Berger Paints India Ltd", "Mr. Arun. C.S", "arjuncs@freshersworld.com"),
    ("Bhansali Engineering Polymers Ltd", "Priyanka Sule", "priyankasule@bhansaliabs.com"),
    ("Black Bird Solutions", "Mr. Zakir", "blackbirdzakir@gmail.com>"),
    ("BNP Paribas", "Pooja.G.Joshi.", "pooja.joshi@asia.bnpparibas.com"),
    ("BNY Mellon", "Karthikeyan Selvamoni", "karthikeyan.selvamoni@bnymellon.com"),
    ("Byju's", "Mr. Md. Sharukhan", "md.shahrukhkhan@byjus.com"),
    ("Cango Networks", "Kalaiselvi.S", "kalaiselvi.s@cangonetworks.com"),
    ("Capgemini", "Vaibhav Deshpande", "vaibhav.deshpande@capgemini.com"),
    ("CGI Information Systems and Management Consultants Pvt Ltd.", "Venket Balaji | Sr Consultant", "venket.balaji@hirepro.in"),
    ("Chain-Sys", "Mr. Sathish. M.S.", "sathish.ms@chainsys.com"),
    ("Citrisys Solutions", "Nisanth", "nnair@citrisys.com"),
    ("Cocubes Technologies Pvt Ltd", "Mr. Hasan Fuaad Sadaq", "hasan.fuaad@cocubes.com"),
    ("Coffee Day Group", "Mr. Sharanyan. R", "sharanyan.r@coffeeday.com"),
    ("Cognizant Technology Solutions", "Mr. Anand", "anand.r2@cognizant.com"),
    ("Cornerstone International(Australian Internship)", "Sudhakar", "learn@cornerstone.edu.in"),
    ("Covenant Consultants", "Ankita Das", "ankita@covenantindia.net"),
    ("CSS Corp.", "Srivathsan Raju", "<srivathsan.raju@csscorp.com>"),
    ("Indus Teqsite P.Ltd", "V.Udayakumar", "udaya.kumar@industeqsite.com"),
    ("Domex e-Data Pvt Ltd.", "V.N. Satheesh Kumar", "careers@domexdata.in"),
    ("Dorma India Pvt. Ltd", "S Sathyanarayanan", "sathya.srinivasan@dormakaba.com"),
    ("Ducima Analytics Pvt. Ltd.", "Deepthi N", "info@ducimaanalytics.com"),
    ("Earnst & Young", "Mr. Haribabu", "hari1.babu@in.ey.com"),
    ("Eattributes", "Raja. B", "brajacse13@gmail.com"),
    ("eLItmusEvaluation Pvt.Ltd", "Nikhil", "elitmus.tpo4@gmail.com"),
    ("Eltech Appliances P Ltd. ( Formerly ETA)", "Mr. Nafeez", "nafeez@eltechappliances.com"),
    ("EmbedUR Systems", "Venkatesh", "venkateshm@embedur.com"),
    ("Episource India Pvt. Ltd.", "Ramesh J", "ramesh.jayakumar@episource.com"),
    ("Fangs Technology (VIVO)", "Mr. Murali. B", "bbmuralivivoglobal@gmail.com"),
    ("Godrej Boyce Mfg. Co. Ltd.", "Mr. Kamal Sharma", "sharmak@godrej.com"),
    ("GRE Edge - Valued Epistemics Pvt. Ltd.", "Mr. Hariharan. M", "hariharan.mourougan@vept.com"),
    ("Hewlett Packard", "Shankar Kannan", "shankar.kannan@@hp.com"),
    ("Hewlett Packard Enterprise", "Namrata Konwar", "konwar@hpe.com>"),
    ("ICICI Securities Limited", "Preetha Prasad. S", "preetha.prasad@icicisecurities.com"),
    ("iNautix Technologies", "Rama Damodharan", "rdamodharan@inautix.co.in"),
    ("INDUSIND BANK", "John Franklin", "john.franklin@indusind.com"),
    ("InfoCepts Technology", "Saima Siddiqui", "ssiddiqui@infocepts.com"),
    ("Infosys Technologies", "Aditi Sondhi", "aditi.sondhi@infosys.com"),
    ("IRIS KPO Resourcing (I) Pvt. Ltd", "Reshma", "reshma.k@iriskpo.in"),
    ("Jaro Educations", "Hafreena", "afreena.s@jaro.in"),
    ("Just Dial .Com", "Vinay Kurella", "vinay.kurella@justdial.com"),
    ("Kaar Technologies", "Rajkumar Shanmugam", "brajkumar@kaar.com"),
    ("Kotak Life Insurance", "Ms. Aina Chowdry", "aaina.chowdhury@kotak.com"),
    ("L & T Infotech", "Kavitha Raman", "kavitha.raman@lntinfotech.com"),
    ("Logwiz Institue of Shipping & Logistics", "Radhika", "radhika@logwiz.in"),
    ("Matrimony.com (Talentsprint Pvt Ltd)", "Sravani.Bandanapudi,", "sravani.b@talentsprint.com"),
    ("Merino Industries P. Ltd.", "Mr. Senthil Kumar Diwakar", "hrchennai@merinoindia.com"),
    ("Mindtree", "Ashok Kumar", "ashok.muniraj@mindtree.com"),
    ("Motherson Automative Tech", "Purusothaman", "purushothaman@matec.motherson.com"),
    ("National Payments Corporation of India (NPCI)", "Ritu Sharma", "ritu.sharma@npci.org.in"),
    ("Neeyamo Enterprise Solutions", "Subapriya", "subapriya.pandiarajan@neeyamo.com"),
    ("Newgen Software", "Karthikeyan Selvamoni", "info@newgensoft.com"),
    ("Ohlook", "Gurunathan Murugan", "hello@ohlook.in"),
    ("OODa Industrial Productes", "Vijayan", "ooagvs@gmail.com"),
    ("Pathfront Consulting Services", "Suthakar", "suthakar@pathfront.in"),
    ("Pratian Technologies (India) Pvt. Ltd", "Sathish", "info@pratian.com"),
    ("RCk Techiees", "Sathish", "contact@rcktechiees.com"),
    ("Renault Nissan Tech. & Business Centre India Pvt Ltd.", "Tripathy Sharmistra", "sarmista.tripathy@rntbci.com"),
    ("Revature Consultancy Services P.Ltd.", "Senthil Kumar", "senthil@revature.com"),
    ("Rivigo", "Sharleena S", "sharleena.s@rivigo.com"),
    ("Samsung R & D", "Mr.Gupta. S", "sid.gupta@samsung.com"),
    ("Sanmar Group", "Rajeswari", "ssr3@sanmargroup.com"),
    ("SCALEUPP", "ROYSTON EBENEZER", "@e-helium.com"),
    ("Schneider Electrci India", "Amcat", "customercare.in@schneider-electric.com"),
    ("SP Robotics", "Human Resource", "info@sproboticworks.com"),
    ("Surya Informatics Solutions P.Ltd", "Human Resource", "hr@suryainfomatics.com"),
    ("Syntel India Ltd.", "Robin Jacob", "robin_jacob@syntelinc.com"),
    ("Technovation", "Suresh", "suresh@sstechnovation.in"),
    ("Things Cloud", "Team Leader", "contact@thethingscloud.com"),
    ("Torry Harris", "Prabhu. K", "hirings@htbs.com"),
    ("Virtusa", "Naveen Sahaya William", "naveenwilliam@virtusa.com"),
    ("Voltech HR Services Pvt Ltd.", "Mr.Muthukumar", "muthukumar@launchpadonline.in"),
    ("Wipro Technologies", "Sudharshan", "sudharshan.suresh@wipro.com"),
    ("Zoho Corporation", "Mr. Shankar S", "shankar.s@zohocorp.com"),
    ("METROLABS", "Sivakumar M", "siva@metrolabs.biz"),
    ("BANKZONE", "ALEX", "alex@bankzone.co.in"),
    ("waves group of companies", "Abhishek", "wavesamma@gmail.com"),
    ("RNDMFG", "LALITHA A", "info@rndmfg.com"),
    ("PickZY Software Pvt Ltd", "ArulJothi&Soundariya", "hr@pickzy.com"),
    ("Bright Star Educational Institution", "Reena", "info@brightstarinst.com"),
    ("CADD Centre Training Services", "Johnsi Kingsly", "hr@cadd.co.in"),
    ("Pentad Management Services Pvt Ltd", "Kumar", "avagroupsindia@gmail.com"),
    ("Raga Designers", "Sriram", "hr@ragadesigners.com"),
    ("Unlimited Innovations India Pvt. Ltd.", "Anushashri", "anushashri@ubtiinc.com"),
    ("NewAge Software and Solutions (I) Pvt Ltd", "Vijayaragavan P", "vijayaragavan.p@newage-global.com"),
    ("RediSolve Software Pvt. Ltd.", "Nihal Lazarus", "hr@redisolve.com/nihallazarus@redisolve.com"),
    ("Zebronics India Pvt Ltd", "Aparna", "hr.info@zebronics.com"),
    ("GOLDEN ENTERPRISES", "NISHANT", "rec@golden-enterprises.co.in"),
    ("Synergy Eduservices (A venture of Lekhguru Infosol Pvt Ltd)", "Vaishakh Nair", "vaishakh.n@synergyeduservices.com"),
    ("Bankbazaar.com", "Sathish Kumar", "sathish.kumar@bankbazaar.com"),
    ("Manpower consultancy", "Daniel", "daniel.kumar@manpower.co.in"),
    ("TVS Training", "Krishna", "krishnakumar.p@tvsts.com"),
    ("TECH MAHINDRA FOUNDATION", "JEROME", "jerome.a@sonayukti.com"),
    ("Tropical Consultants", "Office", "consult@tchvac.in"),
    ("Theja Projects", "Ethirajulu", "thejachennai@gmail.com"),
    ("Dev Max Energy", "MD", "devmaxenergy@gmail.com"),
    ("Apollo Power Systems", "Vadivel", "infoblr@apollopowersystems.com"),
    ("Pioneer Design & Engineering Pvt Ltd", "Office", "info@pioneerdesign.in"),
    ("Ozone VAC", "Pandey", "sales@aacsysengineers.com"),
    ("AC People HVAC Pvt. Ltd.", "Fazlur Rahman", "office@acpeople.com"),
    ("Globe Components Pvt. Ltd.", "Jayanthi", "globesteels@globe-india.com"),
    ("AVTEC Limited", "Office", "corporate@avtec.in"),
    ("Jai Bajali Control Gears Pvt. Ltd.", "HR", "dchandramohan@jaibalaji.firm.in"),
    ("Enmac Systems Pvt. Ltd.", "Pravin Sridhar", "info@enmac.in"),
    ("Gemini Cooling Systems Projects Pvt. Ltd.", "Surender", "sayanihari@yahoo.com geminicoolingsystem@gmail.com"),
    ("Dominair Systems", "Moses Inbaraj", "info@dominairsystems.com danielj@dominairsystems.com dominairsystems@yahoo.com"),
    ("Mohan Mutha Infrastructure Pvt Ltd", "Vikram Babu", "mutha@mmexports.com"),
    ("Vembu Technologies", "Hema Sathia. S,", "hema@employabilitybridge.com"),
    ("Gibraltor Technologies", "Mohamed Abdul Hakeem", "hakeem@gibraltartech.net"),
    ("Vee Technologies", "Abdul Rahuman", "abdulrahuman.a@veetechnologies.com"),
    ("Qspiders / Jspiders", "Ashwini Ramakrishna", "ashwini.r@qspiders.com"),
    ("Wipro HR Services", "Sathish, Cocubes", "sathish.kumar@cocubes.com"),
    ("Data Software Research Company Pvt Ltd(DSRC)", "Hemant.S", "hemant.s@dsrc.co.in"),
    ("JBM Group of Companies", "K.Tamilselvan", "tamilselvan.karthikeyan@jbmgroup.com"),
    ("Tiger Analytics", "HR Team", "info@tigeranalytics.com"),
    ("Valued Epistemics (GREedge)", "Dharshan S S", "dharshan.sinniah@vepl.com"),
    ("No Paper Forms", "Pooja Ahuja", "pooja.ahuja@nopaperforms.com"),
    ("HealthWatch Telediagnostics Pvt Ltd", "T N Ravi Shankar", "tnravishankar@chcgroup.in"),
    ("SSF Plastic India Pvt. Ltd", "Shelly Louis", "info@ssfp.com"),
    ("S10 HealthCare", "Mr. Anand/Ms. Nushrath Banu", "hr@s10health.com"),
    ("TVS Electronics Ltd.", "Krithiga S", "s.krithiga@tvs-e.in"),
    ("VNAI - Venkata", "Srinivasu", "srinivasu@vnai.in"),
    ("Bitcot", "Ashish", "ashish04.jain@gmail.com"),
    ("BATL International Inc.", "Mani Bharathi / Monica", "hr@brewedatthelab.com"),
    ("Focus Academy Career Enhancement (FACE)", "Nishalini K", "nishalini.kumarasamy@focusacademy.in"),
    ("Verizon Data Services India", "Balamurugan", "verizon@verizon.com"),
    ("NSK Bearing India Pvt. Ltd", "Raghu", "raghupathi-a@nsk.com"),
    ("PathFront LLP", "D.Pradhaban", "pradhaban@pathfront.in"),
    ("Data Patterns India Pvt. Ltd", "V.Udayakumar", "karthick@datapatterns.co.in"),
    ("Computer Age Management Services P. Ltd. ( CAMS)", "Priscilla Mam,", "priscilla.a@camsonline.com>"),
    ("Seventhsense Technologies", "Kannan U.", "hr@7stl.com via yahoo.com"),
    ("Life Cell", "Lognathan", "loganathan.ra@lifecell.in"),
    ("Sensiple Software Solutions", "Swati SIngh", "swati.s@sensiple.com"),
    ("Sutherland Global Services", "Ashwin", "ashwin.kausic@sutherlandglobal.com"),
    ("GGS Information Services", "Gokulnath", "gokulnath.ravichandran@ggsinc.com"),
    ("Ameex Technologies", "Mouna M", "mouna.mohanraj@ameexusa.com"),
    ("Molclone Labs Pvt Ltd.", "Vishvash C", "vishvash.c@cocubes.com"),
    ("HCL Technologies", "Swathika. R", "swathikara@hcl.com"),
    ("Practo Healthcare", "Nikhil", "nikhil@freshersworld.com"),
    ("Polyhose Tofle Pvt Ltd", "T. ArunKumar", "arunt@myanatomy.in"),
    ("Aurous HealthCare CRO", "M. Shanmuganathan", "crc.a@auroushealthcare.com"),
    ("Datamatics Global Services Ltd", "Team Lead", "info@datamaticsinc.com"),
    ("Rubber Skill Development Council", "Pritha Biswas", "pritha.biswas@rsdcindia.in"),
    ("Sitel Group", "Thiru", "thirumurugan.k@sitel.com"),
    ("American Megatrends", "P.Senthil Kumar", "senthilkumarp@amiindia.co.in"),
    ("Jamna Auto Industreis Ltd", "Manish Singh", "manish.singh@jaispring.com"),
    ("ZF India Pvt Ltd.", "Mradula Jadia", "mradula.jadia.experiseit@zf.co"),
    ("Solvers India", "Abdul Aleem", "hr@solversindia.com"),
    ("IIFL Finance Ltd", "Simon Davis S", "simondavis.s@iifl.com"),
    ("Muthoot Finance pvt Ltd", "Dharanimohan", "recruitncni@muthootgroup.com, ncni@muthootgroup.com"),
    ("DIYAINFOTECH", "KASIVISWANATH", "kasidiyahr@gmail.com"),
    ("EmployabilityBridge", "M Aswin Yegappan", "aswin@employabilitybridge.com"),
    ("Rankitright Media", "Sathish S", "sathish@rirm.in"),
    ("FASTLAB KNOWLEDGE TRANSFER SOLUTIONS PRIVATE LIMITED", "ARUMUGAM", "jobs@fastlab.in"),
    ("Servicecare Pvt Ltd", "Girish G", "girish@servicecare.in"),
    ("RWD", "Bhavna Asrani", "bhavna.rwd@gmail.com"),
    ("KATHIR SUDHIR AUTOMATION SOLUTIONS", "KARTHIGEYAN.S", "manager@kathirsudhirautomation.com"),
    ("Elior India", "A Hariharan", "hariharan.a@elior.co.in"),
    ("Rubicon skill development", "Pavithra", "pavithraj@my-rubicon.com"),
    ("ManpowerGroup", "sandeep k", "sandeep.k@manpower.co.in"),
    ("EBMS SOLUTIONS PVT LIMITED", "MOHAMED HR", "hr@ebms.co.in"),
    ("Om Innovation Call Service Pvt.Ltd", "Chandra Sai", "chandra.sai@ominnovation.com"),
    ("Ecare India Pvt Ltd", "Aparajitha Rangarajan", "career@ecareindia.com, aparajitha.r@ecareindia.com"),
    ("Zalaris ASA", "Paul Kirubakaran P", "paul.kirubakarn@zalaris.com"),
    ("AMIGAIT TECHNOLOGIES (OPC) PRIVATE LIMITED", "Sindhu S", "hr.chennai@amigatechnologies.com"),
    ("Shield groups", "Suresh", "suruki007@gmail.com"),
]
